### ISSUE TITLE
TD1 Issues

### ISSUE THREAD

**Issue by ghost** [nverstaevel/M1IM_PgStruct1#1]
### 1.5: 

- Is c needed (calculating the area of a rhombus)? [link](https://github.com/nverstaevel/M1IM_PgStruct1/blob/67099b19964c3983ebeb329a65fbf3a0aac1b4fb/TD/1.5_geometrie.ipynb#L101)
- Missing third variable needed for the volume [link](https://github.com/nverstaevel/M1IM_PgStruct1/blob/67099b19964c3983ebeb329a65fbf3a0aac1b4fb/TD/1.5_geometrie.ipynb#L169)
- Need more precision for the pyramid base (square base, rectangle base, base measurments) [link](https://github.com/nverstaevel/M1IM_PgStruct1/blob/67099b19964c3983ebeb329a65fbf3a0aac1b4fb/TD/1.5_geometrie.ipynb#L217)

### 1.10:

- doubled file [link](https://github.com/nverstaevel/M1IM_PgStruct1/blob/2023_2024/TD/1.10_ageCaptain-Copy1.ipynb?short_path=0393691)

### 1.11:

- doubled file [link](https://github.com/nverstaevel/M1IM_PgStruct1/blob/2023_2024/TD/1.11_teamRocket-Copy1.ipynb)
- wrong result in example [link](https://github.com/nverstaevel/M1IM_PgStruct1/blob/67099b19964c3983ebeb329a65fbf3a0aac1b4fb/TD/1.11_teamRocket-Copy1.ipynb#L50), 42 should be replaced with 40 => 14//3 * 10 = 40

**Comment by ghost** [comment]
## Precisions: 
### 1.9: 

- doubled file [link](https://github.com/nverstaevel/M1IM_PgStruct1/blob/2023_2024/TD/1.9_newHope-Copy1.ipynb)

🚨**for duplicate files, checkpoint files (.ipynb_checkpoints folder) are using the [...]-Copy1.ipynb**🚨

**Comment by LaurentMarsan** [comment]
**1.2:** 
plein de fautes : algoritme, permetant, monaie...

**Comment by LaurentMarsan** [comment]
>     * wrong result in example [link](https://github.com/nverstaevel/M1IM_PgStruct1/blob/67099b19964c3983ebeb329a65fbf3a0aac1b4fb/TD/1.11_teamRocket-Copy1.ipynb#L50), 42 should be replaced with 40 => 14//3 * 10 = 40
1.11: Sujet mal lu (mais c'est compliqué): c'est bien 42.
